using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace RagnaForge.Agent.Core.Implementation;

public static class SemanticPatchPlanner
{
    private static readonly Regex QuotedReplaceRegex = new(
        @"(?is)\b(replace|substitua|substituir|troque|alterar|altere)\b.+?['""](?<old>[^'""]+)['""].+?\b(with|por|para)\b.+?['""](?<new>[^'""]+)['""]",
        RegexOptions.Compiled);

    private static readonly Regex SetJsonRegex = new(
        @"(?is)\b(set|defina|ajuste|alterar|altere)\b\s+(?<key>[A-Za-z0-9_.-]+)\s+\b(to|para|como)\b\s+(?<value>.+)$",
        RegexOptions.Compiled);

    private static readonly Regex AddMarkdownSectionRegex = new(
        @"(?is)\b(add|adicionar|criar)\b\s+(section|secao|se[cç][aã]o)\s+['""]?(?<title>[^:'""]+)['""]?\s*:?\s*(?<body>.*)$",
        RegexOptions.Compiled);

    private static readonly Regex AddLineRegex = new(
        @"(?is)\b(add|adicionar|inserir)\b\s+(line|linha)\s+['""](?<line>[^'""]+)['""]",
        RegexOptions.Compiled);

    public static SemanticPatchPlan Plan(
        ImplementationRequest request,
        LanguageCapability capability,
        string? currentContent,
        string resolvedPath,
        Func<string, string, string> formatter)
    {
        if (!string.IsNullOrWhiteSpace(request.Content))
        {
            var content = formatter(resolvedPath, request.Content);
            return BuildPlan("direct-content", "file", "Explicit content supplied by caller.", content, 0.82, "medium", currentContent, request, resolvedPath);
        }

        if (!string.IsNullOrWhiteSpace(request.Template))
        {
            var content = capability.ScaffoldGenerator(new LanguageScaffoldRequest
            {
                TargetPath = resolvedPath,
                Template = request.Template,
                Title = request.Title,
                Name = request.Name,
                Description = request.Description ?? request.Instruction
            });
            return BuildPlan("template-scaffold", "file", "Template scaffold generated by language capability.", content, 0.93, "low", currentContent, request, resolvedPath);
        }

        if (string.IsNullOrWhiteSpace(currentContent))
            return NeedsCodexRepair("target_missing_or_empty", "No current content is available and no content/template was supplied.");

        if (string.IsNullOrWhiteSpace(request.Instruction))
            return NeedsCodexRepair("instruction_missing", "No semantic instruction was supplied.");

        var instruction = request.Instruction.Trim();
        if (instruction.Contains("Instruction noted", StringComparison.OrdinalIgnoreCase))
            return NeedsCodexRepair("instruction_noted_requested", "Instruction-noted patches are explicitly blocked.");

        if (TryBuildQuotedReplacement(currentContent, instruction, out var replaced))
            return BuildPlan("replace-literal", "symbol-or-text", "Instruction mapped to a literal replacement.", formatter(resolvedPath, replaced), 0.78, "medium", currentContent, request, resolvedPath);

        if (Path.GetExtension(resolvedPath).Equals(".json", StringComparison.OrdinalIgnoreCase) &&
            TryBuildJsonSet(currentContent, instruction, out var jsonUpdated))
        {
            return BuildPlan("json-set", "config-key", "Instruction mapped to a JSON key update.", formatter(resolvedPath, jsonUpdated), 0.82, "medium", currentContent, request, resolvedPath);
        }

        if (Path.GetExtension(resolvedPath).Equals(".md", StringComparison.OrdinalIgnoreCase) &&
            TryBuildMarkdownSection(currentContent, instruction, out var markdownUpdated))
        {
            return BuildPlan("markdown-section", "document-section", "Instruction mapped to a Markdown section update.", formatter(resolvedPath, markdownUpdated), 0.8, "low", currentContent, request, resolvedPath);
        }

        if (TryBuildLineAppend(currentContent, instruction, out var appended))
            return BuildPlan("append-line", "file-line", "Instruction mapped to a concrete line append.", formatter(resolvedPath, appended), 0.7, "medium", currentContent, request, resolvedPath);

        return NeedsCodexRepair("semantic_intent_not_supported", "Setimmo could not produce a semantic patch for this instruction.");
    }

    private static bool TryBuildQuotedReplacement(string currentContent, string instruction, out string updated)
    {
        updated = currentContent;
        var match = QuotedReplaceRegex.Match(instruction);
        if (!match.Success)
            return false;

        var oldValue = match.Groups["old"].Value;
        var newValue = match.Groups["new"].Value;
        if (string.IsNullOrWhiteSpace(oldValue) || string.Equals(oldValue, newValue, StringComparison.Ordinal))
            return false;

        if (!currentContent.Contains(oldValue, StringComparison.Ordinal))
            return false;

        updated = currentContent.Replace(oldValue, newValue, StringComparison.Ordinal);
        return !string.Equals(updated, currentContent, StringComparison.Ordinal);
    }

    private static bool TryBuildJsonSet(string currentContent, string instruction, out string updated)
    {
        updated = currentContent;
        var match = SetJsonRegex.Match(instruction);
        if (!match.Success)
            return false;

        try
        {
            var node = JsonNode.Parse(currentContent) as JsonObject;
            if (node is null)
                return false;

            var segments = match.Groups["key"].Value.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (segments.Length == 0)
                return false;

            var target = node;
            for (var i = 0; i < segments.Length - 1; i++)
            {
                if (target[segments[i]] is not JsonObject child)
                    return false;
                target = child;
            }

            target[segments[^1]] = ParseJsonValue(match.Groups["value"].Value.Trim());
            updated = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + Environment.NewLine;
            return !string.Equals(updated, currentContent, StringComparison.Ordinal);
        }
        catch
        {
            return false;
        }
    }

    private static JsonNode? ParseJsonValue(string value)
    {
        var trimmed = value.Trim().TrimEnd('.');
        if (trimmed.Equals("true", StringComparison.OrdinalIgnoreCase)) return JsonValue.Create(true);
        if (trimmed.Equals("false", StringComparison.OrdinalIgnoreCase)) return JsonValue.Create(false);
        if (int.TryParse(trimmed, out var intValue)) return JsonValue.Create(intValue);
        if (double.TryParse(trimmed, out var doubleValue)) return JsonValue.Create(doubleValue);
        return JsonValue.Create(trimmed.Trim('"', '\''));
    }

    private static bool TryBuildMarkdownSection(string currentContent, string instruction, out string updated)
    {
        updated = currentContent;
        var match = AddMarkdownSectionRegex.Match(instruction);
        if (!match.Success)
            return false;

        var title = match.Groups["title"].Value.Trim();
        var body = match.Groups["body"].Value.Trim();
        if (string.IsNullOrWhiteSpace(title))
            return false;

        var section = "## " + title + Environment.NewLine + Environment.NewLine +
            (string.IsNullOrWhiteSpace(body) ? "Conteudo pendente de revisao." : body) + Environment.NewLine;
        updated = currentContent.TrimEnd() + Environment.NewLine + Environment.NewLine + section;
        return true;
    }

    private static bool TryBuildLineAppend(string currentContent, string instruction, out string updated)
    {
        updated = currentContent;
        var match = AddLineRegex.Match(instruction);
        if (!match.Success)
            return false;

        var line = match.Groups["line"].Value.Trim();
        if (string.IsNullOrWhiteSpace(line))
            return false;

        updated = currentContent.TrimEnd() + Environment.NewLine + line + Environment.NewLine;
        return !string.Equals(updated, currentContent, StringComparison.Ordinal);
    }

    private static SemanticPatchPlan BuildPlan(
        string intent,
        string targetKind,
        string reason,
        string content,
        double baseConfidence,
        string riskLevel,
        string? currentContent,
        ImplementationRequest request,
        string resolvedPath)
    {
        var quality = PatchQualityGate.Evaluate(currentContent, content, request, resolvedPath);
        var confidence = quality.Valid ? ImplementationConfidenceScorer.Score(baseConfidence, riskLevel, quality) : 0.2;
        return new SemanticPatchPlan
        {
            Status = quality.Valid ? "planned" : "needs_codex_repair",
            Intent = intent,
            TargetKind = targetKind,
            Reason = reason,
            TargetContent = quality.Valid ? content : null,
            RequiresCodexReview = confidence < 0.9 || riskLevel is "medium" or "high" or "critical",
            NeedsCodexRepair = !quality.Valid || confidence < 0.5,
            SemanticConfidence = confidence,
            PatchQuality = quality,
            RiskLevel = quality.Valid ? riskLevel : "high",
            Advice = quality.Valid
                ? ["Review diff before apply.", "Run relevant tests before apply."]
                : ["Ask Codex to repair the semantic patch.", "Do not apply this operation."]
        };
    }

    private static SemanticPatchPlan NeedsCodexRepair(string code, string reason) => new()
    {
        Status = "needs_codex_repair",
        Intent = code,
        TargetKind = "unknown",
        Reason = reason,
        RequiresCodexReview = true,
        NeedsCodexRepair = true,
        SemanticConfidence = 0.1,
        RiskLevel = "high",
        PatchQuality = new PatchQualityReport
        {
            Valid = false,
            Classification = "non_semantic_patch",
            Reason = reason,
            Blockers = ["non_semantic_patch"]
        },
        Advice = ["Use Codex-supervised repair to generate a real semantic patch."]
    };
}

public static class PatchQualityGate
{
    public static PatchQualityReport Evaluate(string? before, string after, ImplementationRequest request, string path)
    {
        var report = new PatchQualityReport { Valid = true, Classification = "semantic", Reason = "Patch changes target content." };

        if (string.IsNullOrWhiteSpace(after))
            AddBlocker(report, "empty_patch", "Patch target content is empty.");

        if (after.Contains("Instruction noted", StringComparison.OrdinalIgnoreCase))
            AddBlocker(report, "instruction_noted_patch", "Instruction-noted placeholder patches are blocked.");

        if (before is not null && string.Equals(before, after, StringComparison.Ordinal))
            AddBlocker(report, "empty_diff", "Patch does not change target content.");

        if (OnlyAddsCommentsOrTodos(before, after, path))
            AddBlocker(report, "comment_or_todo_only_patch", "Patch only adds comments/TODOs and is not a semantic implementation.");

        if (!string.IsNullOrWhiteSpace(request.Instruction) &&
            request.Instruction.Contains("api", StringComparison.OrdinalIgnoreCase) &&
            Path.GetExtension(path).Equals(".md", StringComparison.OrdinalIgnoreCase))
        {
            report.Warnings.Add("Instruction mentions API while target is documentation; Codex review required.");
        }

        if (report.Blockers.Count > 0)
        {
            report.Valid = false;
            report.Classification = "non_semantic_patch";
            report.Reason = string.Join(" ", report.Blockers);
        }

        return report;
    }

    private static void AddBlocker(PatchQualityReport report, string code, string reason)
    {
        report.Blockers.Add(code);
        report.Warnings.Add(reason);
    }

    private static bool OnlyAddsCommentsOrTodos(string? before, string after, string path)
    {
        if (before is null)
            return false;

        var beforeLines = before.Replace("\r\n", "\n").Split('\n').ToHashSet(StringComparer.Ordinal);
        var addedLines = after.Replace("\r\n", "\n").Split('\n')
            .Where(line => !beforeLines.Contains(line))
            .Select(line => line.Trim())
            .Where(line => line.Length > 0)
            .ToList();

        if (addedLines.Count == 0)
            return false;

        return addedLines.All(line => IsCommentOrTodo(line, path));
    }

    private static bool IsCommentOrTodo(string line, string path)
    {
        if (line.Contains("TODO", StringComparison.OrdinalIgnoreCase))
            return true;

        var ext = Path.GetExtension(path).ToLowerInvariant();
        return ext switch
        {
            ".cs" or ".ts" or ".tsx" or ".js" or ".jsx" or ".java" or ".c" or ".cpp" or ".h" or ".hpp" or ".php" or ".lua" => line.StartsWith("//") || line.StartsWith("/*") || line.StartsWith("*") || line.StartsWith("--"),
            ".ps1" or ".sh" or ".bash" or ".py" => line.StartsWith("#"),
            ".md" => line.StartsWith("<!--") || line.StartsWith("TODO", StringComparison.OrdinalIgnoreCase),
            _ => false
        };
    }
}

public static class ImplementationConfidenceScorer
{
    public static double Score(double baseConfidence, string riskLevel, PatchQualityReport quality)
    {
        var score = baseConfidence;
        if (quality.Warnings.Count > 0) score -= 0.08;
        score -= riskLevel switch
        {
            "critical" => 0.35,
            "high" => 0.25,
            "medium" => 0.1,
            _ => 0
        };

        return Math.Clamp(Math.Round(score, 2), 0, 1);
    }
}
