using RagnaForge.Agent.Core.Canon;
using RagnaForge.Agent.Core.Commands;

namespace RagnaForge.Agent.Core.Governance;

public static class OperationGovernanceProfiles
{
    public static OperationGovernanceAssessment EvaluateWithoutValidation(
        string operationName,
        GlobalCanonCheckResult? canon = null,
        bool applyEngineImplemented = false,
        bool rollbackEngineImplemented = false,
        bool productionApplyEnabled = false,
        bool pathScopeValidated = true,
        bool pathTraversalDetected = false,
        bool genericShellExposed = false,
        bool externalWriteRequested = false,
        bool secretsDetected = false,
        bool buildPassed = true,
        bool testsPassed = true,
        bool destructiveOperationRequested = false,
        bool requirePlanForApply = false,
        bool requireDiffForApply = false,
        bool requireRollbackForApply = false,
        bool hasPlan = true,
        bool hasDiff = true,
        bool hasRollback = true,
        string productionEnvironment = "local",
        bool productionHumanApprovalRecorded = false,
        bool productionApprovalHashMatches = false,
        bool productionApprovalExpired = false,
        bool productionScopeAuthorized = true,
        bool productionAuditLogAvailable = true,
        bool productionOperationClassified = true,
        bool productionRiskWithinLimit = true)
    {
        return Evaluate(
            operationName,
            canon,
            validation: null,
            validationStateKnown: false,
            applyEngineImplemented,
            rollbackEngineImplemented,
            productionApplyEnabled,
            pathScopeValidated,
            pathTraversalDetected,
            genericShellExposed,
            externalWriteRequested,
            secretsDetected,
            buildPassed,
            testsPassed,
            destructiveOperationRequested,
            requirePlanForApply,
            requireDiffForApply,
            requireRollbackForApply,
            hasPlan,
            hasDiff,
            hasRollback,
            productionEnvironment,
            productionHumanApprovalRecorded,
            productionApprovalHashMatches,
            productionApprovalExpired,
            productionScopeAuthorized,
            productionAuditLogAvailable,
            productionOperationClassified,
            productionRiskWithinLimit);
    }

    public static OperationGovernanceAssessment EvaluateValidated(
        string operationName,
        GlobalCanonCheckResult canon,
        ValidationDecisionSummary validation,
        bool applyEngineImplemented = false,
        bool rollbackEngineImplemented = false,
        bool productionApplyEnabled = false,
        bool pathScopeValidated = true,
        bool pathTraversalDetected = false,
        bool genericShellExposed = false,
        bool externalWriteRequested = false,
        bool secretsDetected = false,
        bool buildPassed = true,
        bool testsPassed = true,
        bool destructiveOperationRequested = false,
        bool requirePlanForApply = false,
        bool requireDiffForApply = false,
        bool requireRollbackForApply = false,
        bool hasPlan = true,
        bool hasDiff = true,
        bool hasRollback = true,
        string productionEnvironment = "local",
        bool productionHumanApprovalRecorded = false,
        bool productionApprovalHashMatches = false,
        bool productionApprovalExpired = false,
        bool productionScopeAuthorized = true,
        bool productionAuditLogAvailable = true,
        bool productionOperationClassified = true,
        bool productionRiskWithinLimit = true)
    {
        ArgumentNullException.ThrowIfNull(canon);
        ArgumentNullException.ThrowIfNull(validation);

        return Evaluate(
            operationName,
            canon,
            validation,
            validationStateKnown: true,
            applyEngineImplemented,
            rollbackEngineImplemented,
            productionApplyEnabled,
            pathScopeValidated,
            pathTraversalDetected,
            genericShellExposed,
            externalWriteRequested,
            secretsDetected,
            buildPassed,
            testsPassed,
            destructiveOperationRequested,
            requirePlanForApply,
            requireDiffForApply,
            requireRollbackForApply,
            hasPlan,
            hasDiff,
            hasRollback,
            productionEnvironment,
            productionHumanApprovalRecorded,
            productionApprovalHashMatches,
            productionApprovalExpired,
            productionScopeAuthorized,
            productionAuditLogAvailable,
            productionOperationClassified,
            productionRiskWithinLimit);
    }

    public static OperationGovernanceAssessment EvaluateApplyRequestPreview() =>
        Evaluate(
            "apply",
            canon: null,
            validation: new ValidationDecisionSummary
            {
                SafeForReadOnlyWork = true,
                SafeForDryRun = true,
                SafeForApply = true
            },
            validationStateKnown: true,
            applyEngineImplemented: true,
            rollbackEngineImplemented: true,
            productionApplyEnabled: false,
            pathScopeValidated: true,
            pathTraversalDetected: false,
            genericShellExposed: false,
            externalWriteRequested: false,
            secretsDetected: false,
            buildPassed: true,
            testsPassed: true,
            destructiveOperationRequested: false,
            requirePlanForApply: true,
            requireDiffForApply: true,
            requireRollbackForApply: true,
            hasPlan: false,
            hasDiff: false,
            hasRollback: false,
            productionEnvironment: "local",
            productionHumanApprovalRecorded: false,
            productionApprovalHashMatches: false,
            productionApprovalExpired: false,
            productionScopeAuthorized: true,
            productionAuditLogAvailable: true,
            productionOperationClassified: true,
            productionRiskWithinLimit: true);

    public static OperationGovernanceAssessment EvaluateRollbackRequestPreview() =>
        Evaluate(
            "rollback",
            canon: null,
            validation: new ValidationDecisionSummary
            {
                SafeForReadOnlyWork = true,
                SafeForDryRun = true,
                SafeForApply = true
            },
            validationStateKnown: true,
            applyEngineImplemented: true,
            rollbackEngineImplemented: true,
            productionApplyEnabled: false,
            pathScopeValidated: true,
            pathTraversalDetected: false,
            genericShellExposed: false,
            externalWriteRequested: false,
            secretsDetected: false,
            buildPassed: true,
            testsPassed: true,
            destructiveOperationRequested: false,
            requirePlanForApply: false,
            requireDiffForApply: false,
            requireRollbackForApply: false,
            hasPlan: true,
            hasDiff: true,
            hasRollback: true,
            productionEnvironment: "local",
            productionHumanApprovalRecorded: false,
            productionApprovalHashMatches: false,
            productionApprovalExpired: false,
            productionScopeAuthorized: true,
            productionAuditLogAvailable: true,
            productionOperationClassified: true,
            productionRiskWithinLimit: true);

    private static OperationGovernanceAssessment Evaluate(
        string operationName,
        GlobalCanonCheckResult? canon,
        ValidationDecisionSummary? validation,
        bool validationStateKnown,
        bool applyEngineImplemented,
        bool rollbackEngineImplemented,
        bool productionApplyEnabled,
        bool pathScopeValidated,
        bool pathTraversalDetected,
        bool genericShellExposed,
        bool externalWriteRequested,
        bool secretsDetected,
        bool buildPassed,
        bool testsPassed,
        bool destructiveOperationRequested,
        bool requirePlanForApply,
        bool requireDiffForApply,
        bool requireRollbackForApply,
        bool hasPlan,
        bool hasDiff,
        bool hasRollback,
        string productionEnvironment,
        bool productionHumanApprovalRecorded,
        bool productionApprovalHashMatches,
        bool productionApprovalExpired,
        bool productionScopeAuthorized,
        bool productionAuditLogAvailable,
        bool productionOperationClassified,
        bool productionRiskWithinLimit)
    {
        var context = new OperationGovernanceContext
        {
            OperationName = operationName,
            CanonSafeForReadOnlyWork = canon?.SafeForReadOnlyWork ?? true,
            CanonSafeForDryRun = canon?.SafeForDryRun ?? true,
            CanonSafeForApply = canon?.SafeForApply ?? true,
            ValidationStateKnown = validationStateKnown,
            ValidationSafeForReadOnlyWork = validation?.SafeForReadOnlyWork ?? true,
            ValidationSafeForDryRun = validation?.SafeForDryRun ?? true,
            ValidationSafeForApply = validation?.SafeForApply ?? true,
            ApplyEngineImplemented = applyEngineImplemented,
            RollbackEngineImplemented = rollbackEngineImplemented,
            ProductionApplyEnabled = productionApplyEnabled,
            ProductionEnvironment = productionEnvironment,
            ProductionHumanApprovalRecorded = productionHumanApprovalRecorded,
            ProductionApprovalHashMatches = productionApprovalHashMatches,
            ProductionApprovalExpired = productionApprovalExpired,
            ProductionScopeAuthorized = productionScopeAuthorized,
            ProductionAuditLogAvailable = productionAuditLogAvailable,
            ProductionOperationClassified = productionOperationClassified,
            ProductionRiskWithinLimit = productionRiskWithinLimit,
            PathScopeValidated = pathScopeValidated,
            PathTraversalDetected = pathTraversalDetected,
            GenericShellExposed = genericShellExposed,
            ExternalWriteRequested = externalWriteRequested,
            SecretsDetected = secretsDetected,
            BuildPassed = buildPassed,
            TestsPassed = testsPassed,
            DestructiveOperationRequested = destructiveOperationRequested,
            RequirePlanForApply = requirePlanForApply,
            RequireDiffForApply = requireDiffForApply,
            RequireRollbackForApply = requireRollbackForApply,
            HasPlan = hasPlan,
            HasDiff = hasDiff,
            HasRollback = hasRollback
        };

        return OperationGovernanceEngine.EvaluateDefault(context);
    }
}
